"""
This script demonstrates how to use the JsonOutputParser from LangChain to ensure
the language model's output is structured as a JSON object.
"""

from langchain_huggingface import ChatHuggingFace, HuggingFaceEndpoint
from dotenv import load_dotenv
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import JsonOutputParser

# Load environment variables (e.g., HuggingFace API token)
load_dotenv()

# Define the HuggingFace endpoint model
llm = HuggingFaceEndpoint(
    repo_id="google/gemma-2-2b-it",
    task="text-generation"
)

# Initialize the ChatHuggingFace wrapper for the language model
model = ChatHuggingFace(llm=llm)

# Initialize the JSON output parser to format the model's response as JSON
parser = JsonOutputParser()

# Create a prompt template with instructions for the desired format
template = PromptTemplate(
    template='Give me 5 facts about {topic} \n {format_instruction}',
    input_variables=['topic'],
    # Inject format instructions generated by the JsonOutputParser
    partial_variables={'format_instruction': parser.get_format_instructions()}
)

# Combine the prompt template, model, and output parser into a single processing chain
chain = template | model | parser

# Execute the chain with a specific topic
result = chain.invoke({'topic': 'black hole'})

# Print the final parsed JSON result
print(result)
