"""
This script demonstrates how to use the PydanticOutputParser from LangChain to extract
and validate structured data into a Pydantic model.
"""

from langchain_huggingface import ChatHuggingFace, HuggingFaceEndpoint
from dotenv import load_dotenv
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import PydanticOutputParser
from pydantic import BaseModel, Field

# Load environment variables (e.g., HuggingFace API token)
load_dotenv()

# Define the HuggingFace endpoint model
llm = HuggingFaceEndpoint(
    repo_id="google/gemma-2-2b-it",
    task="text-generation"
)

# Initialize the ChatHuggingFace wrapper for the language model
model = ChatHuggingFace(llm=llm)

# Define a Pydantic model for the expected output structure
class Person(BaseModel):
    name: str = Field(description='Name of the person')
    age: int = Field(gt=18, description='Age of the person')
    city: str = Field(description='Name of the city the person belongs to')

# Initialize the Pydantic output parser with the target model
parser = PydanticOutputParser(pydantic_object=Person)

# Create a prompt template requesting specific information along with format instructions
template = PromptTemplate(
    template='Generate the name, age and city of a fictional {place} person \n {format_instruction}',
    input_variables=['place'],
    # Inject format instructions generated by the PydanticOutputParser
    partial_variables={'format_instruction': parser.get_format_instructions()}
)

# Combine the prompt template, model, and output parser into a single processing chain
chain = template | model | parser

# Execute the chain to generate and parse data about a fictional person
final_result = chain.invoke({'place': 'sri lankan'})

# Print the validated Pydantic object (or its dictionary representation)
print(final_result)
