"""
This script demonstrates how to use the StructuredOutputParser from LangChain 
to define and extract a specific schema (list of key-value pairs) from the model's output.
"""

from langchain_huggingface import ChatHuggingFace, HuggingFaceEndpoint
from dotenv import load_dotenv
from langchain_core.prompts import PromptTemplate
from langchain.output_parsers import StructuredOutputParser, ResponseSchema

# Load environment variables (e.g., HuggingFace API token)
load_dotenv()

# Define the HuggingFace endpoint model
llm = HuggingFaceEndpoint(
    repo_id="google/gemma-2-2b-it",
    task="text-generation"
)

# Initialize the ChatHuggingFace wrapper for the language model
model = ChatHuggingFace(llm=llm)

# Define the expected output schema using ResponseSchema objects
schema = [
    ResponseSchema(name='fact_1', description='Fact 1 about the topic'),
    ResponseSchema(name='fact_2', description='Fact 2 about the topic'),
    ResponseSchema(name='fact_3', description='Fact 3 about the topic'),
]

# Initialize the structured output parser with the defined schema
parser = StructuredOutputParser.from_response_schemas(schema)

# Create a prompt template including instructions on how to format the output based on the schema
template = PromptTemplate(
    template='Give 3 facts about {topic} \n {format_instruction}',
    input_variables=['topic'],
    # Inject format instructions generated by the StructuredOutputParser
    partial_variables={'format_instruction': parser.get_format_instructions()}
)

# Combine the prompt template, model, and output parser into a single processing chain
chain = template | model | parser

# Execute the chain to get structured facts about a topic
result = chain.invoke({'topic': 'black hole'})

# Print the resulting parsed dictionary
print(result)